/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.List;
import modelo.Linea;
import modelo.Punto;

/**
 *
 * @author HP
 */
public class TableroPanel extends javax.swing.JPanel {

    private List<Punto> puntos;
    private List<Linea> lineas;
    private String tipoPintado;
    public Punto puntoA;
    public Punto puntoB;

    public TableroPanel() {
        this.lineas = new ArrayList<>();
        initComponents();
    }

    public void generarPuntos(List<Punto> puntos) {
        this.puntos = puntos;
        repaint();
    }

    public void generaLineas(Linea linea) {
        //  tipoPintado = "generarLineas";
        lineas.add(linea);
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (lineas != null) {
            Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(new BasicStroke(5));
            for (int i = 0; i < lineas.size(); i++) {
                g.setColor(Color.ORANGE);
                Punto puntoA = lineas.get(i).getPuntoA();
                Punto puntoB = lineas.get(i).getPuntoB();
                g.drawLine(puntoA.getX() + 10 / 2,
                        puntoA.getY() + 10 / 2,
                        puntoB.getX() + 10 / 2,
                        puntoB.getY() + 10 / 2);
            }
        }

        for (int i = 0; i < puntos.size(); i++) {
            g.setColor(Color.WHITE);
            int posicionX = puntos.get(i).getX();
            int posicionY = puntos.get(i).getY();
            if (puntoA != null && puntoA.equals(puntos.get(i))
                    || puntoB != null && puntoB.equals(puntos.get(i))) {
                g.setColor(Color.GREEN);
            }
            g.fillOval(posicionX, posicionY, 10, 10);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
