/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.util.List;
import modelo.Punto;

/**
 *
 * @author HP
 */
public class TableroPanel extends javax.swing.JPanel {

    private List<Punto> puntos;
    private String tipoPintado;

    public TableroPanel() {
        initComponents();
    }

    public void generarPuntos(List<Punto> puntos) {
        tipoPintado = "generarPuntos";
        this.puntos = puntos;
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (tipoPintado.equals("generarPuntos")) {
            g.setColor(Color.WHITE);
            for (int i = 0; i < puntos.size(); i++) {
                int posicionX = puntos.get(i).getX();
                int posicionY = puntos.get(i).getY();
                g.fillOval(posicionX, posicionY, 10, 10);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
